---
name: CITEST
# Commenting out to add workflow dispatch
#on: [push, pull_request]
on:
  workflow_dispatch:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - env:
          AZURE_CREDENTIALS: '{
                              "clientId": "4af8af72-ce1a-440b-a41c-cee649199449",
                              "clientSecret": "mwxApLXmmJZa11qphZjJs.SMkMPNFvR_9O",
                              "subscriptionId": "7d149fba-cc81-4bab-8461-ea09919d78cd",
                              "tenantId": "8dcc1c85-50c8-41bb-ba73-be0bf36f827f",
                              "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
                              "resourceManagerEndpointUrl": "https://management.azure.com/",
                              "activeDirectoryGraphResourceId": "https://graph.windows.net/",
                              "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
                              "galleryEndpointUrl": "https://gallery.azure.com/",
                              "managementEndpointUrl": "https://management.core.windows.net/"
                              }'
        #run: echo $AZURE_CREDENTIALS
        uses: azure/login@v1
        with:
          creds: ${AZURE_CREDENTIALS}
          
      - uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az account show