---
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
    env:
      AZURE_VAULT_NAME: "kv${{ github.run_id }}-${{ matrix.node-version }}"
      AZURE_DEFAULTS_GROUP: "${{ secrets.KEYVAULT_RESOURCE_GROUP }}"
      AZURE_DEFAULTS_LOCATION: "westeurope"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - uses: azure/CLI@v1
        with:
          inlineScript: |
            az account show
            az keyvault create --name ${{ env.AZURE_VAULT_NAME }}
            echo "OBJECT_ID=$(az keyvault list | jq '.[0].properties.accessPolicies[0].objectId')" >> $GITHUB_ENV

      - uses: azure/CLI@v1
        with:
          inlineScript: |
            # set keyvault policies
            az keyvault set-policy -n ${{ env.AZURE_VAULT_NAME }} --key-permissions backup create decrypt delete encrypt get import list purge recover restore sign unwrapKey update verify wrapKey --object-id ${{ env.OBJECT_ID }}
            # set secret policies
            az keyvault set-policy -n ${{ env.AZURE_VAULT_NAME }} --secret-permissions backup delete get list purge recover restore set --object-id ${{ env.OBJECT_ID }}
            # set certificates policies
            az keyvault set-policy -n ${{ env.AZURE_VAULT_NAME }} --certificate-permissions backup create delete deleteissuers get getissuers import list listissuers managecontacts manageissuers purge recover restore setissuers update --object-id ${{ env.OBJECT_ID }}

      - env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: npm run test:ci
        continue-on-error: true

      - uses: azure/CLI@v1
        with:
          inlineScript: |
            az keyvault delete --name ${{ env.AZURE_VAULT_NAME }}

  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
